 # This is a basic workflow to help you get started with Actions

name: Update API

# Controls when the workflow will run
on:
  # Triggers the workflow on pull request events on the "main" branch 
  #   push:
  #     branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  update-api:
    name: update api on 3scale
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Workflow tasks par ofthe job.
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - name: Check out repository
      uses: actions/checkout@v3
      with:
        path: main

      # Run the 3scale import task.
    - name: install 3scale toolbox
      uses: froberge/3scaletoolbox-action@v0.0.2
      with:
        threeScale-token: ${{ secrets.THREESCALE_TOKEN }}
        threeScale-domain: ${{ secrets.THREESCALE_DOMAIN }}
        api-file: main/openapi.json
        devkey-token: ${{ secrets.DEVKEY_TOKEN }}
